services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
    ports:
      - "8080:8080"

  ui:
    build:
      context: ..
      dockerfile: docker/Dockerfile.streamlit
    environment:
      - API_URL=http://api:8080
    ports:
      - "8502:8501"
    depends_on:
      - api
