global:
  scrape_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'flask_api'
    metrics_path: /metrics
    static_configs:
      - targets: 
        - api:5000
  
  - job_name: 'prometheus'
    static_configs:
      - targets: 
        - localhost:9090